### ISSUE TITLE
`default_controller.call_representation` can only handle kwargs, not args

### ISSUE THREAD

**Issue by UNakade** [fdrtd/fdrtd#6]
When a patch request is made from the client side with some args, the args are not transferred to the server. Only kwargs work. 
Steps to recreate:
1. on server side
```python
python -m fdrtd.webserver --port=5000
```
2. on client side
```python
import representation
api=representation.Api("http://localhost:5000")
barrier=api.create(microservice="Barrier")
barrier.create('some_token') 
# this fails. on the client side, the body is {'args': ('some_token',), 'kwargs': {}}, 
# but on the server, if checked when default_controller.call_representation
# is called, it's just {'kwargs': {}}. the error shown on the server is:
# ERROR:connexion.operations.openapi3:Body property 'args' not defined in 
# body schema. 
# If both args and kwargs are entered, the error still exists
barrier.create(tokens="some_token") # this works
```
I have not been able to figure out the cause behind this as I have limited knowledge of how the server works. But from the `openapi.yaml` file, the schema specification for ArgsKwargs does look fine.

**Comment by Ballhausen** [comment]
Thanks for raising this issue. Confirmed.

The problem was caused by the following lines in openapi.yaml:

```
args:
  type: array
  items: {}
```

According to the documentation at https://swagger.io/docs/specification/data-models/data-types/ this should have been the definition of an array of arbitrary types.

There is a temporary fix in place, making the schema ArgsKwargs into a freeform dictionary.

If you update the fdrtd server, the problem should be gone. The client-side representation library and its API definition need not be touched.
